name: flutter_open_scad
description: "Create OpenSCAD models in a GUI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  backstreets_widgets: ^0.35.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
